---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/konradasb/github_exporter/build.Revision={{ .ShortCommit }}
      - -X github.com/konradasb/github_exporter/build.Date={{ .CommitDate }}
      - -X github.com/konradasb/github_exporter/build.Version={{ .Version }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
