---
name: main

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: konradasb/github_exporter:${{ github.sha1 }}
          push: true
